ARC-63: Static analysis as rake
ArchivistProject/archivist-api pull request #2
Opened 2016-10-24 20:24 UTC by Redwards34

Adding in the various gem files with bullet and jslint currently disabled.

2016-10-24 20:42 UTC, mr2ert requested changes
Please update these

2016-10-24 20:42 UTC, mr2ert commented on Gemfile
> +  #gem 'bullet' # Has an issue with no support mongoid v6.0.0, re-asses later
Could you change this to:

    # TODO: Has an issue with no support mongoid v6.0.0, re-asses later
    #gem 'bullet'

To keep with the current TODO style?

2016-10-24 20:42 UTC, mr2ert commented on config/environments/development.rb
> +  #config.after_initialize do
Could you also add

    # TODO: Has an issue with no support mongoid v6.0.0, re-asses later

Here too?

2016-10-24 20:43 UTC, mr2ert commented on docker-compose.yml
> +version: '2.0'
Why did you need to make this change?  Was it not working before?

2016-10-24 20:47 UTC, mr2ert commented on Rakefile
> +    RuboCop::RakeTask.new
Can we run brakeman here as well? http://brakemanscanner.org/docs/rake/  We should update the `desc` as well if we do this.

2016-10-24 20:48 UTC, Redwards34 commented on docker-compose.yml
> +version: '2.0'
There was an error message previously, but it is no longer necessary.

2016-10-24 21:32 UTC, mr2ert commented on Rakefile
> +task :static_analysis, :output_files do |t, args|
Could we move this to `lib/tasks/static_analysis.rb`?

2016-10-24 21:59 UTC, mr2ert approved these changes

2016-10-24 22:32 UTC, mr2ert commented
:shipit: Thanks for handling this.  Might want to add something to the README to say how to run this before you squash merge.

2016-10-25 00:20 UTC, Redwards34 commented
Updating README to include info about the newly added static analysis task

2016-10-25 00:21 UTC, merged